//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaintainAccount.UPSOnline {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UPSOnline.UPSOnlineSoap")]
    public interface UPSOnlineSoap {
        
        // CODEGEN: Generating message contract since element name addr1 from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateClassifyAddressXML", ReplyAction="*")]
        MaintainAccount.UPSOnline.ValidateClassifyAddressXMLResponse ValidateClassifyAddressXML(MaintainAccount.UPSOnline.ValidateClassifyAddressXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateClassifyAddressXML", ReplyAction="*")]
        System.Threading.Tasks.Task<MaintainAccount.UPSOnline.ValidateClassifyAddressXMLResponse> ValidateClassifyAddressXMLAsync(MaintainAccount.UPSOnline.ValidateClassifyAddressXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateClassifyAddress", ReplyAction="*")]
        MaintainAccount.UPSOnline.ValidateClassifyAddressResponse ValidateClassifyAddress(MaintainAccount.UPSOnline.ValidateClassifyAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateClassifyAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<MaintainAccount.UPSOnline.ValidateClassifyAddressResponse> ValidateClassifyAddressAsync(MaintainAccount.UPSOnline.ValidateClassifyAddressRequest request);
        
        // CODEGEN: Generating message contract since element name addr1 from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClassifyAddressXML", ReplyAction="*")]
        MaintainAccount.UPSOnline.ClassifyAddressXMLResponse ClassifyAddressXML(MaintainAccount.UPSOnline.ClassifyAddressXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClassifyAddressXML", ReplyAction="*")]
        System.Threading.Tasks.Task<MaintainAccount.UPSOnline.ClassifyAddressXMLResponse> ClassifyAddressXMLAsync(MaintainAccount.UPSOnline.ClassifyAddressXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClassifyAddress", ReplyAction="*")]
        MaintainAccount.UPSOnline.ClassifyAddressResponse ClassifyAddress(MaintainAccount.UPSOnline.ClassifyAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClassifyAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<MaintainAccount.UPSOnline.ClassifyAddressResponse> ClassifyAddressAsync(MaintainAccount.UPSOnline.ClassifyAddressRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateClassifyAddressXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateClassifyAddressXML", Namespace="http://tempuri.org/", Order=0)]
        public MaintainAccount.UPSOnline.ValidateClassifyAddressXMLRequestBody Body;
        
        public ValidateClassifyAddressXMLRequest() {
        }
        
        public ValidateClassifyAddressXMLRequest(MaintainAccount.UPSOnline.ValidateClassifyAddressXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateClassifyAddressXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addr1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string addr2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string state;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string zip5;
        
        public ValidateClassifyAddressXMLRequestBody() {
        }
        
        public ValidateClassifyAddressXMLRequestBody(string addr1, string addr2, string city, string state, string zip5) {
            this.addr1 = addr1;
            this.addr2 = addr2;
            this.city = city;
            this.state = state;
            this.zip5 = zip5;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateClassifyAddressXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateClassifyAddressXMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public MaintainAccount.UPSOnline.ValidateClassifyAddressXMLResponseBody Body;
        
        public ValidateClassifyAddressXMLResponse() {
        }
        
        public ValidateClassifyAddressXMLResponse(MaintainAccount.UPSOnline.ValidateClassifyAddressXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateClassifyAddressXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CPUserControls.UPSOnline.Response ValidateClassifyAddressXMLResult;
        
        public ValidateClassifyAddressXMLResponseBody() {
        }
        
        public ValidateClassifyAddressXMLResponseBody(CPUserControls.UPSOnline.Response ValidateClassifyAddressXMLResult) {
            this.ValidateClassifyAddressXMLResult = ValidateClassifyAddressXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateClassifyAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateClassifyAddress", Namespace="http://tempuri.org/", Order=0)]
        public MaintainAccount.UPSOnline.ValidateClassifyAddressRequestBody Body;
        
        public ValidateClassifyAddressRequest() {
        }
        
        public ValidateClassifyAddressRequest(MaintainAccount.UPSOnline.ValidateClassifyAddressRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateClassifyAddressRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addr1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string addr2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string state;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string zip5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string zip4;
        
        public ValidateClassifyAddressRequestBody() {
        }
        
        public ValidateClassifyAddressRequestBody(string addr1, string addr2, string city, string state, string zip5, string zip4) {
            this.addr1 = addr1;
            this.addr2 = addr2;
            this.city = city;
            this.state = state;
            this.zip5 = zip5;
            this.zip4 = zip4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateClassifyAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateClassifyAddressResponse", Namespace="http://tempuri.org/", Order=0)]
        public MaintainAccount.UPSOnline.ValidateClassifyAddressResponseBody Body;
        
        public ValidateClassifyAddressResponse() {
        }
        
        public ValidateClassifyAddressResponse(MaintainAccount.UPSOnline.ValidateClassifyAddressResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateClassifyAddressResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ValidateClassifyAddressResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string addr1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string addr2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string state;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string zip5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string zip4;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int status;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int classification;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int count;
        
        public ValidateClassifyAddressResponseBody() {
        }
        
        public ValidateClassifyAddressResponseBody(int ValidateClassifyAddressResult, string addr1, string addr2, string city, string state, string zip5, string zip4, int status, int classification, int count) {
            this.ValidateClassifyAddressResult = ValidateClassifyAddressResult;
            this.addr1 = addr1;
            this.addr2 = addr2;
            this.city = city;
            this.state = state;
            this.zip5 = zip5;
            this.zip4 = zip4;
            this.status = status;
            this.classification = classification;
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClassifyAddressXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClassifyAddressXML", Namespace="http://tempuri.org/", Order=0)]
        public MaintainAccount.UPSOnline.ClassifyAddressXMLRequestBody Body;
        
        public ClassifyAddressXMLRequest() {
        }
        
        public ClassifyAddressXMLRequest(MaintainAccount.UPSOnline.ClassifyAddressXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClassifyAddressXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addr1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string addr2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string state;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string zip5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string zip4;
        
        public ClassifyAddressXMLRequestBody() {
        }
        
        public ClassifyAddressXMLRequestBody(string addr1, string addr2, string city, string state, string zip5, string zip4) {
            this.addr1 = addr1;
            this.addr2 = addr2;
            this.city = city;
            this.state = state;
            this.zip5 = zip5;
            this.zip4 = zip4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClassifyAddressXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClassifyAddressXMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public MaintainAccount.UPSOnline.ClassifyAddressXMLResponseBody Body;
        
        public ClassifyAddressXMLResponse() {
        }
        
        public ClassifyAddressXMLResponse(MaintainAccount.UPSOnline.ClassifyAddressXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClassifyAddressXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CPUserControls.UPSOnline.Response ClassifyAddressXMLResult;
        
        public ClassifyAddressXMLResponseBody() {
        }
        
        public ClassifyAddressXMLResponseBody(CPUserControls.UPSOnline.Response ClassifyAddressXMLResult) {
            this.ClassifyAddressXMLResult = ClassifyAddressXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClassifyAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClassifyAddress", Namespace="http://tempuri.org/", Order=0)]
        public MaintainAccount.UPSOnline.ClassifyAddressRequestBody Body;
        
        public ClassifyAddressRequest() {
        }
        
        public ClassifyAddressRequest(MaintainAccount.UPSOnline.ClassifyAddressRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClassifyAddressRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addr1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string addr2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string state;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string zip5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string zip4;
        
        public ClassifyAddressRequestBody() {
        }
        
        public ClassifyAddressRequestBody(string addr1, string addr2, string city, string state, string zip5, string zip4) {
            this.addr1 = addr1;
            this.addr2 = addr2;
            this.city = city;
            this.state = state;
            this.zip5 = zip5;
            this.zip4 = zip4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClassifyAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClassifyAddressResponse", Namespace="http://tempuri.org/", Order=0)]
        public MaintainAccount.UPSOnline.ClassifyAddressResponseBody Body;
        
        public ClassifyAddressResponse() {
        }
        
        public ClassifyAddressResponse(MaintainAccount.UPSOnline.ClassifyAddressResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClassifyAddressResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ClassifyAddressResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int classification;
        
        public ClassifyAddressResponseBody() {
        }
        
        public ClassifyAddressResponseBody(int ClassifyAddressResult, int classification) {
            this.ClassifyAddressResult = ClassifyAddressResult;
            this.classification = classification;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UPSOnlineSoapChannel : MaintainAccount.UPSOnline.UPSOnlineSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UPSOnlineSoapClient : System.ServiceModel.ClientBase<MaintainAccount.UPSOnline.UPSOnlineSoap>, MaintainAccount.UPSOnline.UPSOnlineSoap {
        
        public UPSOnlineSoapClient() {
        }
        
        public UPSOnlineSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UPSOnlineSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UPSOnlineSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UPSOnlineSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MaintainAccount.UPSOnline.ValidateClassifyAddressXMLResponse MaintainAccount.UPSOnline.UPSOnlineSoap.ValidateClassifyAddressXML(MaintainAccount.UPSOnline.ValidateClassifyAddressXMLRequest request) {
            return base.Channel.ValidateClassifyAddressXML(request);
        }
        
        public CPUserControls.UPSOnline.Response ValidateClassifyAddressXML(string addr1, string addr2, string city, string state, string zip5) {
            MaintainAccount.UPSOnline.ValidateClassifyAddressXMLRequest inValue = new MaintainAccount.UPSOnline.ValidateClassifyAddressXMLRequest();
            inValue.Body = new MaintainAccount.UPSOnline.ValidateClassifyAddressXMLRequestBody();
            inValue.Body.addr1 = addr1;
            inValue.Body.addr2 = addr2;
            inValue.Body.city = city;
            inValue.Body.state = state;
            inValue.Body.zip5 = zip5;
            MaintainAccount.UPSOnline.ValidateClassifyAddressXMLResponse retVal = ((MaintainAccount.UPSOnline.UPSOnlineSoap)(this)).ValidateClassifyAddressXML(inValue);
            return retVal.Body.ValidateClassifyAddressXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MaintainAccount.UPSOnline.ValidateClassifyAddressXMLResponse> MaintainAccount.UPSOnline.UPSOnlineSoap.ValidateClassifyAddressXMLAsync(MaintainAccount.UPSOnline.ValidateClassifyAddressXMLRequest request) {
            return base.Channel.ValidateClassifyAddressXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<MaintainAccount.UPSOnline.ValidateClassifyAddressXMLResponse> ValidateClassifyAddressXMLAsync(string addr1, string addr2, string city, string state, string zip5) {
            MaintainAccount.UPSOnline.ValidateClassifyAddressXMLRequest inValue = new MaintainAccount.UPSOnline.ValidateClassifyAddressXMLRequest();
            inValue.Body = new MaintainAccount.UPSOnline.ValidateClassifyAddressXMLRequestBody();
            inValue.Body.addr1 = addr1;
            inValue.Body.addr2 = addr2;
            inValue.Body.city = city;
            inValue.Body.state = state;
            inValue.Body.zip5 = zip5;
            return ((MaintainAccount.UPSOnline.UPSOnlineSoap)(this)).ValidateClassifyAddressXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MaintainAccount.UPSOnline.ValidateClassifyAddressResponse MaintainAccount.UPSOnline.UPSOnlineSoap.ValidateClassifyAddress(MaintainAccount.UPSOnline.ValidateClassifyAddressRequest request) {
            return base.Channel.ValidateClassifyAddress(request);
        }
        
        public int ValidateClassifyAddress(ref string addr1, ref string addr2, ref string city, ref string state, ref string zip5, ref string zip4, out int status, out int classification, out int count) {
            MaintainAccount.UPSOnline.ValidateClassifyAddressRequest inValue = new MaintainAccount.UPSOnline.ValidateClassifyAddressRequest();
            inValue.Body = new MaintainAccount.UPSOnline.ValidateClassifyAddressRequestBody();
            inValue.Body.addr1 = addr1;
            inValue.Body.addr2 = addr2;
            inValue.Body.city = city;
            inValue.Body.state = state;
            inValue.Body.zip5 = zip5;
            inValue.Body.zip4 = zip4;
            MaintainAccount.UPSOnline.ValidateClassifyAddressResponse retVal = ((MaintainAccount.UPSOnline.UPSOnlineSoap)(this)).ValidateClassifyAddress(inValue);
            addr1 = retVal.Body.addr1;
            addr2 = retVal.Body.addr2;
            city = retVal.Body.city;
            state = retVal.Body.state;
            zip5 = retVal.Body.zip5;
            zip4 = retVal.Body.zip4;
            status = retVal.Body.status;
            classification = retVal.Body.classification;
            count = retVal.Body.count;
            return retVal.Body.ValidateClassifyAddressResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MaintainAccount.UPSOnline.ValidateClassifyAddressResponse> MaintainAccount.UPSOnline.UPSOnlineSoap.ValidateClassifyAddressAsync(MaintainAccount.UPSOnline.ValidateClassifyAddressRequest request) {
            return base.Channel.ValidateClassifyAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<MaintainAccount.UPSOnline.ValidateClassifyAddressResponse> ValidateClassifyAddressAsync(string addr1, string addr2, string city, string state, string zip5, string zip4) {
            MaintainAccount.UPSOnline.ValidateClassifyAddressRequest inValue = new MaintainAccount.UPSOnline.ValidateClassifyAddressRequest();
            inValue.Body = new MaintainAccount.UPSOnline.ValidateClassifyAddressRequestBody();
            inValue.Body.addr1 = addr1;
            inValue.Body.addr2 = addr2;
            inValue.Body.city = city;
            inValue.Body.state = state;
            inValue.Body.zip5 = zip5;
            inValue.Body.zip4 = zip4;
            return ((MaintainAccount.UPSOnline.UPSOnlineSoap)(this)).ValidateClassifyAddressAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MaintainAccount.UPSOnline.ClassifyAddressXMLResponse MaintainAccount.UPSOnline.UPSOnlineSoap.ClassifyAddressXML(MaintainAccount.UPSOnline.ClassifyAddressXMLRequest request) {
            return base.Channel.ClassifyAddressXML(request);
        }
        
        public CPUserControls.UPSOnline.Response ClassifyAddressXML(string addr1, string addr2, string city, string state, string zip5, string zip4) {
            MaintainAccount.UPSOnline.ClassifyAddressXMLRequest inValue = new MaintainAccount.UPSOnline.ClassifyAddressXMLRequest();
            inValue.Body = new MaintainAccount.UPSOnline.ClassifyAddressXMLRequestBody();
            inValue.Body.addr1 = addr1;
            inValue.Body.addr2 = addr2;
            inValue.Body.city = city;
            inValue.Body.state = state;
            inValue.Body.zip5 = zip5;
            inValue.Body.zip4 = zip4;
            MaintainAccount.UPSOnline.ClassifyAddressXMLResponse retVal = ((MaintainAccount.UPSOnline.UPSOnlineSoap)(this)).ClassifyAddressXML(inValue);
            return retVal.Body.ClassifyAddressXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MaintainAccount.UPSOnline.ClassifyAddressXMLResponse> MaintainAccount.UPSOnline.UPSOnlineSoap.ClassifyAddressXMLAsync(MaintainAccount.UPSOnline.ClassifyAddressXMLRequest request) {
            return base.Channel.ClassifyAddressXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<MaintainAccount.UPSOnline.ClassifyAddressXMLResponse> ClassifyAddressXMLAsync(string addr1, string addr2, string city, string state, string zip5, string zip4) {
            MaintainAccount.UPSOnline.ClassifyAddressXMLRequest inValue = new MaintainAccount.UPSOnline.ClassifyAddressXMLRequest();
            inValue.Body = new MaintainAccount.UPSOnline.ClassifyAddressXMLRequestBody();
            inValue.Body.addr1 = addr1;
            inValue.Body.addr2 = addr2;
            inValue.Body.city = city;
            inValue.Body.state = state;
            inValue.Body.zip5 = zip5;
            inValue.Body.zip4 = zip4;
            return ((MaintainAccount.UPSOnline.UPSOnlineSoap)(this)).ClassifyAddressXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MaintainAccount.UPSOnline.ClassifyAddressResponse MaintainAccount.UPSOnline.UPSOnlineSoap.ClassifyAddress(MaintainAccount.UPSOnline.ClassifyAddressRequest request) {
            return base.Channel.ClassifyAddress(request);
        }
        
        public int ClassifyAddress(string addr1, string addr2, string city, string state, string zip5, string zip4, out int classification) {
            MaintainAccount.UPSOnline.ClassifyAddressRequest inValue = new MaintainAccount.UPSOnline.ClassifyAddressRequest();
            inValue.Body = new MaintainAccount.UPSOnline.ClassifyAddressRequestBody();
            inValue.Body.addr1 = addr1;
            inValue.Body.addr2 = addr2;
            inValue.Body.city = city;
            inValue.Body.state = state;
            inValue.Body.zip5 = zip5;
            inValue.Body.zip4 = zip4;
            MaintainAccount.UPSOnline.ClassifyAddressResponse retVal = ((MaintainAccount.UPSOnline.UPSOnlineSoap)(this)).ClassifyAddress(inValue);
            classification = retVal.Body.classification;
            return retVal.Body.ClassifyAddressResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MaintainAccount.UPSOnline.ClassifyAddressResponse> MaintainAccount.UPSOnline.UPSOnlineSoap.ClassifyAddressAsync(MaintainAccount.UPSOnline.ClassifyAddressRequest request) {
            return base.Channel.ClassifyAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<MaintainAccount.UPSOnline.ClassifyAddressResponse> ClassifyAddressAsync(string addr1, string addr2, string city, string state, string zip5, string zip4) {
            MaintainAccount.UPSOnline.ClassifyAddressRequest inValue = new MaintainAccount.UPSOnline.ClassifyAddressRequest();
            inValue.Body = new MaintainAccount.UPSOnline.ClassifyAddressRequestBody();
            inValue.Body.addr1 = addr1;
            inValue.Body.addr2 = addr2;
            inValue.Body.city = city;
            inValue.Body.state = state;
            inValue.Body.zip5 = zip5;
            inValue.Body.zip4 = zip4;
            return ((MaintainAccount.UPSOnline.UPSOnlineSoap)(this)).ClassifyAddressAsync(inValue);
        }
    }
}
